package scoverage

import munit.FunSuite

class Scala213PluginCoverageTest extends FunSuite with MacroSupport {

  test(
    "scoverage should ignore synthetic lazy definitions generated by compiler from by-name implicits"
  ) {
    val compiler = ScoverageCompiler.noPositionValidation
    compiler.compileCodeSnippet(
      """
        |object test {
        |
        |  trait Foo {
        |    def next: Foo
        |  }
        |
        |  object Foo {
        |    implicit def foo(implicit rec: => Foo): Foo =
        |      new Foo { def next = rec }
        |  }
        |
        |  val foo = implicitly[Foo]
        |
        |}
        |
      """.stripMargin
    )
    assert(!compiler.reporter.hasErrors)
    assert(!compiler.reporter.hasWarnings)
  }
}
